### ISSUE TITLE
Using non/exported module functions as completers

### ISSUE THREAD

**Issue by powercode** [lzybkr/TabExpansionPlusPlus#37]
Quite often when writing modules, I want to access internal helper functions in the completers.

The current design does not allow this, as it runs in the scope of tabexpansion++.

Are there any other options that would allow this?

/Staffan

**Comment by lzybkr** [comment]
There aren't any options.  I might have been too restrictive in not wanting to export useful functions - if those helpers were exported from TabExpansion++, then there would be no need to run in the scope of TabExpansion++.

As I'll be removing the attributed function approach soon - basically requiring Register-ArgumentCompleter, I think it makes a lot of sense to address this at the same time.

**Comment by powercode** [comment]
Yes, I think the gain of running in the scope of TabExpansion++ is not even close to how useful it would be to be able to access the module scope.

Is Register-ArgumentCompleter becoming part of PowerShell?

**Comment by lzybkr** [comment]
Closing - the latest version of the module exports the helpers you wanted to use.
