### ISSUE TITLE
Parsing errors in RemoteDesktop PowerShell module

### ISSUE THREAD

**Issue by pcgeek86** [lzybkr/TabExpansionPlusPlus#38]
* Windows Server 2012 R2 (Azure VM)
* WMF 5.0 April 2015

I'm running Update-ArgumentCompleters, and am getting a bunch of parsing errors in the RemoteDesktop PowerShell module that is included with Windows Server.

![image](https://cloud.githubusercontent.com/assets/466713/7361328/967f932e-ed13-11e4-892a-313cd7f08f6c.png)

> VERBOSE: Parse errors: At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\RemoteDesktop\Deployment.psm1:467 char:6
+      [Microsoft.RemoteDesktopServices.Common.RDMSConstants]::RoleServ ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Attribute argument must be a constant or a script block. \n At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\RemoteDesktop\Deployment.psm1:468 char:6
+      [Microsoft.RemoteDesktopServices.Common.RDMSConstants]::RoleServ ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Attribute argument must be a constant or a script block. \n At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\RemoteDesktop\Deployment.psm1:469 char:6
+      [Microsoft.RemoteDesktopServices.Common.RDMSConstants]::RoleServ ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by lzybkr** [comment]
I think these errors are harmless.  I plan on removing the scanning code anyway (along with Update-ArgumentCompleters), and when that is done, these errors will go away too.
