### ISSUE TITLE
Quotes are added to completer result

### ISSUE THREAD

**Issue by pcgeek86** [lzybkr/TabExpansionPlusPlus#40]
I've got a situation where I want to auto-complete (generate) another parameter, based on the auto-completed value of a parameter. For example, a user types:

```
Get-SomeObject -Param1 {TAB}
```

And the auto-completed result is:

```
Get-SomeObject -Param1 Value1 -Param2 Value2
```

The result is **currently** looking like:

```
Get-SomeObject -Param1 'Value1 -Param2 Value2'
```

What I'm looking for is to have the quotes removed from the auto-completed value, because the value actually contains another named parameter definition.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by lzybkr** [comment]
Instead of calling New-CompletionResult, create the CompletionResult yourself (via New-Object), but you'll need to take responsibility for quoting Value1 as needed.  You can see how New-CompletionResult decides if quotes are needed.
