### ISSUE TITLE
Ignore/hide extension for executable files

### ISSUE THREAD

**Issue by totkeks** [lzybkr/TabExpansionPlusPlus#81]
Would it be possible to add a feature that is either configurable or uses $env:PATHEXT to determine which extensions to hide?

E.g. I have a powershell script folder on my $env:PATH and when I complete it, I get `my_script.ps1`, but instead it should only display it as `my_script`, like when I would have defined it as a function.

**Comment by lzybkr** [comment]
I don't have any plans to add features to this module.

At this point, the most important parts of this module are available in PowerShell (as of v5.1) and with PowerShell now being open source, I think enhancements like what you propose should be made [here](https://github.com/PowerShell/PowerShell/issues/new?template=Feature_Request.md).

**Comment by totkeks** [comment]
Thanks for the reply! I will post my feature request over there then. Happy Holidays!
